# 設定コンパイラ設定ファイル
#
# @package jp.co.b-shock.carrot
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

constant/application:
  class: BSDefineConfigCompiler
  params:
    prefix: APP

constant/carrot:
  class: BSDefineConfigCompiler
  params:
    prefix: BS

validate/:
  class: BSValidatorConfigCompiler

menu/:
  class: BSMenuConfigCompiler

server/:
  class: BSDefineConfigCompiler
  params:
    prefix: BS

layout/:
  class: BSLayoutConfigCompiler

styleset/:
  class: BSSerializeConfigCompiler

mobile/:
  class: BSSerializeConfigCompiler

date/:
  class: BSSerializeConfigCompiler

filters:
  class: BSObjectRegisterConfigCompiler

module:
  class: BSSerializeConfigCompiler
