# 設定コンパイラ設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

# 評価する順番に記述

constant/application:
  class: BSDefineConfigCompiler
  params:
    prefix: APP

constant/carrot:
  class: BSDefineConfigCompiler
  params:
    prefix: BS

validate/:
  class: BSValidatorConfigCompiler

menu/:
  class: BSMenuConfigCompiler

server/:
  class: BSDefineConfigCompiler
  params:
    prefix: BS

layout/:
  class: BSLayoutConfigCompiler

filters:
  class: BSObjectRegisterConfigCompiler

.default:
  class: BSSerializeConfigCompiler