# ConfigHandler設定ファイル
#
# @package jp.co.b-shock.carrot
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

constant/application:
  class: BSDefineConfigHandler
  param.prefix: APP

constant/carrot:
  class: BSDefineConfigHandler
  param.prefix: BS

filters:
  class: BSObjectRegisterConfigHandler

module:
  class: BSSerializeConfigHandler

validate/:
  class: BSValidatorConfigHandler

menu/:
  class: BSMenuConfigHandler

server/:
  class: BSDefineConfigHandler
  param.prefix: BS

layout/:
  class: BSLayoutConfigHandler

styleset/:
  class: BSSerializeConfigHandler

mobile/:
  class: BSSerializeConfigHandler

date/:
  class: BSSerializeConfigHandler
