# 設定コンパイラ設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$
# 評価する順番に記述

constant/:
  class: BSDefineConfigCompiler

validate/:
  class: BSValidatorConfigCompiler

layout/:
  class: BSLayoutConfigCompiler

filters:
  class: BSObjectRegisterConfigCompiler

.default:
  class: BSDefaultConfigCompiler