# フィルタ設定ファイル
#
# @package jp.co.b-shock.carrot
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

- class: BSRequestCleaningFilter
    params:
      convert_kana: KVa
      new_line: yes
      reading: yes
      date: yes

