# フィルタ設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

- class: BSNullByteRequestFilter
- class: BSEncodingRequestFilter
- class: BSMagicQuoteRequestFilter
- class: BSNewLineRequestFilter
- class: BSKanaRequestFilter
  params:
    option: KVa
- class: BSReadingRequestFilter
- class: BSDateRequestFilter
- class: BSDeniedUserAgentFilter
  params:
    types:
      - LegacyMozilla

