# メディアタイプ設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

types:
  css: text/css
  csv: text/csv
  dat: application/octet-stream
  eml: message/rfc822
  gif: image/gif
  gz: application/x-gzip
  htm: text/html
  html: text/html
  ini: text/x-ini-file
  jpg: image/jpeg
  jpeg: image/jpeg
  js: text/javascript
  json: application/json
  mime: message/rfc822
  pdf: application/pdf
  php:
  pl:
  pm:
  png: image/png
  rb:
  sql:
  swf: application/x-shockwave-flash
  tgz: application/x-gzip
  tpl:
  ttf: application/x-truetype-font
  txt: text/plain
  yaml: text/yaml
  yml: text/yaml
  xls: application/vnd.ms-excel
  xml: application/xml
  zip: application/zip
