# JavaScriptセット設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

carrot:
  files:
    - elevator
    - prototype
    - scriptaculous/effects
    - ajaxzip2/ajaxzip2
    - prototabs
    - protocalendar/protocalendar
    - protocalendar/lang_ja
    - ObjTree
    - carrot
    - application
