# JavaScriptセット設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

carrot:
  files:
    - carrot
    - elevator
    - prototype
    - scriptaculous/builder
    - scriptaculous/effects
    - scriptaculous/dragdrop
    - scriptaculous/controls
    - scriptaculous/slider
    - scriptaculous/sound
    - ajaxzip2/ajaxzip2
    - prototabs
    - protocalendar/protocalendar
    - protocalendar/lang_ja
    - datepicker
