# バリデータ設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

date:
  class: BSDateValidator
email:
  class: BSMailAddressValidator
empty:
  class: BSEmptyValidator
english:
  class: BSEnglishValidator
file:
  class: BSFileValidator
flag:
  class: BSChoiceValidator
  params:
    choices:
      - 1
html:
  class: BSHTMLFragmentValidator
  params:
    allowed_tags:
      - h1
      - h2
      - h3
      - h4
      - h5
      - h6
      - h7
      - p
      - br
      - table
      - tbody
      - th
      - tr
      - td
      - strike
      - strong
      - em
      - b
      - i
      - u
      - font
      - hr
      - a
      - ul
      - ol
      - li
      - img
image:
  class: BSImageValidator
kana:
  class: BSKanaValidator
longtext:
  class: BSStringValidator
  params:
    max: 65536
pixel:
  class: BSNumberValidator
  params:
    min: 8
    max: 1024
string:
  class: BSStringValidator
  params:
    max: 1024
tel:
  class: BSPhoneNumberValidator
tinytext:
  class: BSStringValidator
  params:
    max: 250
url:
  class: BSURLValidator
year:
  class: BSNumberValidator
  params:
    min: 1912
zipcode:
  class: BSZipcodeValidator

