# フィルタ設定ファイル
#
# @package org.carrot-framework
# @subpackage AdminXMPPBot
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

- class: BSSecurityFilter
  param:
    credential: Admin

- class: BSHostSecurityFilter

- class: BSMenuFilter
