# レーダーチャート 表示色設定
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

background: ivory
chart_border: darkgray
item_label: darkblue
radiation: darkgray
grid_number: olivedrab
rader_border: darkgray
rader_fill: lavender