# スタイルセット設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

carrot.Detail:
  files:
    - carrot
    - carrot.Detail
    - datepicker

carrot.LoginForm:
  files:
    - carrot
    - carrot.LoginForm
