# メニュー設定ファイル - 管理メニュー
#
# @package __PACKAGE__
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

- separator: yes
- module: AdminLog
- module: AdminXMPPBot
- module: DevelopTableReport
- module: DevelopDocumentor
- name: AWStats
  title: アクセスログ解析
  href: /awstats/awstats.pl
  target: _blank
- separator: yes
- name: Logout
  title: ログアウト
  module: Default
  action: Logout