# フィルタ設定ファイル
#
# @package __PACKAGE__
# @author 小石達也 <tkoishi@b-shock.co.jp>

- class: BSFakeUserAgentFilter
- class: BSLegacyUserAgentFilter
#- class: BSPictogramRequestFilter
- class: BSEncodingRequestFilter
- class: BSNewLineRequestFilter
#- class: BSWrongCharactersRequestFilter
- class: BSCookieFilter
  params:
    excluded_actions:
      - Login
- class: BSKanaRequestFilter
  params:
    option: KVa
- class: BSReadingRequestFilter
- class: BSDateRequestFilter
