# アプリケーション定数設定ファイル
#
# @package __PACKAGE__
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

app:
  name:
    ja: __NAME_JA__
    en: __NAME_EN__
  ver: 1.0.0-dev
  bts:
    url: http://redmine.carrot-framework.org/projects/show/carrot

author:
  name: 有限会社 ビーショック
  email: info@b-shock.co.jp

svn:
  url: http://svn.carrot-framework.org/carrot/trunk