# アプリケーション定数設定ファイル
#
# @package __PACKAGE__
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

name:
  ja: __NAME_JA__
  en: __NAME_EN__

ver: 1.0.0-dev

languages:
  - ja

home:
  #href: /index.html

module:
  prefixes:
    - Admin
    - User
    - Develop

secure:
  #module: Default
  #action: Login

feed:
  class: BSAtom10Document

useragent:
  denied:
    types:
      - LegacyNetscape
      - Tasman
    module: Default
    action: Unsupported
