# アプリケーション定数設定ファイル - carrot分
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

carrot:
  name: carrot Framework
  ver: 2.1.40
  bts:
    url: http://redmine.carrot-framework.org/projects/show/carrot

app:
  name:
    ja: unknown
    en: unknown
  ver: unknown
  bts:
    url: http://redmine.carrot-framework.org/projects/show/carrot

debug: yes

languages:
  - ja

home:
  href: /index.html

date:
  timezone: Asia/Tokyo

types:
  file: /etc/httpd/mime.types

serialize:
  storage: default
  serializer: JSON
  keep:
    - BSCounter.*

session:
  storage: default

smarty:
  cache:
    storage: default
    life_time: 300

memcache:
  daemon_name: memcached
  host: unix:///tmp/memcached.sock
  port: 0

net:
  resolvable: yes

smtp:
  host: localhost
  check_addresses: no

xmpp:
  host: localhost

crypt:
  salt: carrot
  engine: blowfish

log:
  loggers:
    - file
    - mail
    - system
  syslog:
    facility: LOCAL6
  mail:
    patterns:
      - BSDatabaseException

image:
  thumbnail:
    bgcolor: black
    type: image/png

pdo:
  query_log_enable: no
  default:
    dsn: sqlite:%BS_VAR_DIR%/db/db.sqlite3
    loggable: yes
  log:
    dsn: sqlite:%BS_VAR_DIR%/db/log.sqlite3
  session:
    dsn: sqlite:%BS_VAR_DIR%/db/session.sqlite3
  serialize:
    dsn: sqlite:%BS_VAR_DIR%/db/serialize.sqlite3

mysql:
  dir: /usr/local

pgsql:
  dir: /usr/local

sqlite3:
  dir: /usr/local

proctools:
  dir: /usr/local

feed:
  class: BSRSS20Document

awstats:
  daily: yes
  server_name_aliases:

module:
  prefixes:
    - Admin
    - User
    - Develop
  default:
    module: Default
    action: Default
  not_found:
    module: Default
    action: NotFound
  secure:
    module: Default
    action: NotFound

