# アプリケーション定数設定ファイル - carrot分
#
# @package jp.co.b-shock.carrot
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

script_encoding: utf-8

carrot:
  ver: 2.0.16

default:
  module: Default
  action: Default

not_found:
  module: Default
  action: NotFound

secure:
  module: Default
  action: NotFound

smarty:
  template_encoding: utf-8

holiday:
  ja:
    class: BSJapaneseHolidayList
    url: http://refits.cgk.affrc.go.jp/tsrv/jp/calendar.php

browscap:
  url: http://browsers.garykeith.com/stream.asp?PHP_BrowsCapINI
