# ホスト別設定ファイル
#
# @package __PACKAGE__
# @author 小石達也 <tkoishi@b-shock.co.jp>

root_url: http://carrot.dev.b-shock.local/
root_url_https: http://carrot2.b-shock.local/
debug: yes

admin:
  email: admin@b-shock.co.jp
  password: $2y$10$iv12Di/l.VParpPiqrWNUuGAhhl1PklXKj2FhkcFtjDyPsiwnAS8q
pdo:
  default:
    uid: root
    password:
view:
  html5: yes
