# ホスト別設定ファイル
#
# @package __PACKAGE__
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

root_url: http://carrot.gisarme.local/
root_url_https: http://carrot.gisarme.local/
debug: yes

admin:
  email: admin@b-shock.co.jp
  jid: pooza@jabber.b-shock.co.jp/carrot
  password: LRSOV7gId+o=
  networks:
    - 192.168.100.0/24

crypt:
  salt: carrot

types:
  #file: %BS_WEBAPP_DIR%/config/mime/mime.types

pdo:
  default:
    #dsn: mysql:host=127.0.0.1;dbname=carrot
    #dsn: pgsql:host=localhost dbname=carrot user=postgres
    uid: root
    password:

smtp:
  host: localhost

awstats:
  log_dir: /var/log/httpd/www.example.com
  server_name_aliases: 

google:
  key: 0vnLqpBQFHLy7J9p/YO40u6wOrTlaV2I
