# ホスト別設定ファイル
#
# @package __PACKAGE__
# @author 小石達也 <tkoishi@b-shock.co.jp>

root_url: http://carrot.kapi.local/
root_url_https: http://carrot.kapi.local/
debug: yes

admin:
  email: admin@b-shock.co.jp
  password: 7e240de74fb1ed08fa08d38063f6a6a91462a815
  networks:
    - 192.168.100.0/24
pdo:
  default:
    #dsn: mysql:host=127.0.0.1;dbname=carrot
    #dsn: pgsql:host=localhost dbname=carrot user=postgres
    uid: root
    password:
awstats:
  log_dir: /var/log/httpd/www.example.com
serialize:
  storage: memcache
session:
  storage: memcache
view:
  html5: yes
