# アプリケーション定数設定ファイル - carrot分
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

carrot:
  name: carrot Framework
  url: http://trac.carrot-framework.org/project/carrot/
  ver: 2.0.60

default:
  module: Default
  action: Default

not_found:
  module: Default
  action: NotFound

secure:
  module: Default
  action: NotFound

mysql:
  dir: /usr/local

pgsql:
  dir: /usr/local

sqlite3:
  dir: /usr/local

browscap:
  url: http://browsers.garykeith.com/stream.asp?PHP_BrowsCapINI

