# アプリケーション定数設定ファイル - carrot分
#
# @package jp.co.b-shock.carrot
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

script_encoding: utf-8

carrot:
  name: carrot Framework
  url: http://trac.b-shock.org/project/carrot/
  ver: 2.0.25

default:
  module: Default
  action: Default

not_found:
  module: Default
  action: NotFound

secure:
  module: Default
  action: NotFound

smarty:
  template_encoding: utf-8

browscap:
  url: http://browsers.garykeith.com/stream.asp?PHP_BrowsCapINI

