# フィルタ設定ファイル
#
# @package jp.co.b-shock.carrot
# @subpackage DevelopDocumentor
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

- class: BSSecurityFilter
  params:
    credential: Develop

- class: BSHostSecurityFilter

- class: BSMenuFilter
  params:
    name: admin
