# モジュール設定ファイル
#
# @package org.carrot-framework
# @subpackage DevelopDocumentor
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

module:
  title_menu: Documentor
  title: Documentorモジュール

actions:
  Generate:
    title: APIドキュメント生成