<?php
/**
 * @package jp.co.b-shock.carrot
 * @subpackage css
 */

BSController::includeLegacy('/pear/HTML/CSS.php');

/**
 * CSS
 *
 * @author 小石達也 <tkoishi@b-shock.co.jp>
 * @copyright (c)b-shock. co., ltd.
 * @version $Id$
 */
class BSStyleSet extends HTML_CSS implements BSRenderer {
	private $files = array();
	private $rules = array();
	private static $stylesets = array();

	/**
	 * コンストラクタ
	 *
	 * @access public
	 * @param string $styleset スタイルセット名
	 */
	public function __construct ($styleset = 'carrot') {
		$this->setCharset();

		$stylesets = self::getStyleSets();
		$files = array();
		$dir = BSController::getInstance()->getDirectory('css');
		if (isset($stylesets[$styleset]['files'])) {
			foreach ($stylesets[$styleset]['files'] as $file) {
				if ($entry = $dir->getEntry($file)) {
					$files[] = $entry;
				}
			}
		} else if ($entry = $dir->getEntry($styleset)) {
			$files[] = $entry;
		}

		foreach ($files as $file) {
			$this->parseFile($file);
		}
	}

	/**
	 * 送信内容を返す
	 *
	 * @access public
	 * @return string 送信内容
	 */
	public function getContents () {
		$contents = array();
		foreach ($this->getRules() as $key => $value) {
			$contents[] = sprintf('@%s "%s";', $key, $value);
		}
		$contents[] = null;
		$contents[] = '/**';
		$contents[] = ' * auth-generated by ' . get_class($this);
		$contents[] = ' * date: ' . BSDate::getNow('Y/m/d H:i:s');
		$contents[] = ' */';
		$contents[] = null;
		$contents[] = null;
		return implode("\n", $contents) . $this->toString();
	}

	/**
	 * メディアタイプを返す
	 *
	 * @access public
	 * @return string メディアタイプ
	 */
	public function getType () {
		return BSTypeList::getType('css') . '; charset=' . $this->getRule('charset');
	}

	/**
	 * 出力可能か？
	 *
	 * @access public
	 * @return boolean 出力可能ならTrue
	 */
	public function validate () {
		return !$this->isError() && $this->getContents();
	}

	/**
	 * エラーメッセージを返す
	 *
	 * @access public
	 * @return string エラーメッセージ
	 */
	public function getError () {
		return $this->_lastError;
	}

	/**
	 * 文字セットを設定する
	 *
	 * @access public
	 * @param string $type 文字セットの種類
	 * @return PEAR_Error エラーが発生した場合はエラーオブジェクトを返す
	 */
	public function setCharset ($type = BS_SCRIPT_ENCODING) {
		$this->setRule('charset', $type);
		return parent::setCharset($type);
	}

	/**
	 * 定義済み@規則を返す
	 *
	 * @access protected
	 * @param string $name @規則の名前
	 * @return string @規則の値
	 */
	protected function getRule ($name) {
		if (isset($this->rules[$name])) {
			return $this->rules[$name];
		}
	}

	/**
	 * 定義済み@規則を全て返す
	 *
	 * @access protected
	 * @return string @規則の値
	 */
	protected function getRules () {
		return $this->rules;
	}

	/**
	 * @規則を設定する ごく単純な、文字列で指定するものだけ
	 *
	 * @access protected
	 * @param string $name @規則の名前
	 * @param string $value @規則の値
	 */
	protected function setRule ($name, $value) {
		if ($value != '') {
			$this->rules[$name] = $value;
		} else {
			unset($this->rules[$name]);
		}
	}

	/**
	 * CSS文字列をパースする
	 *
	 * @access public
	 * @param string $str CSS文字列
	 * @param boolean $duplicates 重複を許すか
	 */
	function parseString ($str, $duplicates = false) {
		// "@charset" 等を保護する
		if (preg_match('/@(charset) *[\'"]?([^;\'"]+)[\'"]?;/', $str, $matches)) {
			$this->setRule($matches[1], $matches[2]);
			$str = str_replace($matches[0], null, $str);
		}

		parent::parseString($str, $duplicates);
	}

	/**
	 * CSSファイルを登録する
	 *
	 * @access public
	 * @param BSFile|string $file CSSファイル、又はその名前
	 * @param boolean $duplicates 重複を許すか
	 */
	public function parseFile ($file, $duplicates = false) {
		if ($file instanceof BSFile) {
			// 素通り
		} else if (Toolkit::isPathAbsolute($file)) {
			$file = new BSFile($file);
		} else if ($entry = BSController::getInstance()->getDirectory('css')->getEntry($file)) {
			$file = $entry;
		} else {
			throw new BSCSSException('CSSファイル "%s" が読み込めません。', $file);
		}

		if ($this->addFile($file)) {
			if ($error = parent::parseFile($file->getPath(), $duplicates)) {
				if ($error instanceof PEAR_Error) {
					throw new BSCSSException($error->getMessage());
				} else {
					throw new BSCSSException('原因不明のエラーが発生。');
				}
			}
		}
	}

	/**
	 * 登録ファイルを配列に代入する
	 *
	 * @access private
	 * @param BSFile $file CSSファイル又はINIファイル
	 * @return boolean 代入を実際に行ったらTrue
	 */
	private function addFile (BSFile $file) {
		if (!$file->isReadable()) {
			throw new BSCSSException('%sが読み込めません。', $file);
		}
		foreach ($this->files as $fileCurrent) {
			if ($file->getPath() == $fileCurrent->getPath()) {
				return false;
			}
		}
		$this->files[] = $file;
		return true;
	}

	/**
	 * 全てのスタイルセットを返す
	 *
	 * @access private
	 * @return string[][] スタイルセットを配列で返す
	 * @static
	 */
	private static function getStyleSets () {
		if (!self::$stylesets) {
			$stylesets = array();
			require_once(ConfigCache::checkConfig('config/styleset/application.ini'));
			require_once(ConfigCache::checkConfig('config/styleset/carrot.ini'));
			self::$stylesets = $stylesets;
		}
		return self::$stylesets;
	}

	/**
	 * 全てのスタイルセットの名前を返す
	 *
	 * @access public
	 * @return string[] スタイルセットの名前を配列で返す
	 * @static
	 */
	public static function getStyleSetNames () {
		$names = array_keys(self::getStyleSets());
		$names[] = 'carrot';
		sort($names);
		return $names;
	}
}

/* vim:set tabstop=4 ai: */
?>