# フィルタ設定ファイル
#
# @package jp.co.b-shock.carrot
# @subpackage DevelopTableReport
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

- class: BSSecurityFilter
  param.credential: Develop
- class: BSHostSecurityFilter
- class: BSMenuFilter
  param.name: admin
