# ホスト別設定ファイル
#
# @package jp.co.b-shock.carrot
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

root_url: http://carrot.galbacura-ref.local/
root_url_https: http://carrot.galbacura-ref.local/
debug: yes
#resolvable: yes

admin:
  email: admin@b-shock.co.jp
  jid: pooza@jabber.b-shock.co.jp/carrot
  password: 47bce5c74f589f4867dbd57e9ca9f808
  networks:
    - 192.168.0.0/24
    - 192.168.1.0/24

author:
  name: 有限会社 ビーショック
  email: info@b-shock.co.jp
  jid: carrot.galbacura-ref@jabber.b-shock.co.jp/carrot
  password: aaa

crypt:
  engine: blowfish
  salt: carrot

types:
  #file: /etc/httpd/mime.types
  #file: %BS_WEBAPP_DIR%/config/mime/mime.types

pdo:
  #query_log_enable: no
  default:
    dsn: mysql:host=127.0.0.1;dbname=carrot
    #dsn: pgsql:host=localhost dbname=carrot user=postgres
    #dsn: sqlite:%BS_VAR_DIR%/db/db.sqlite3
    uid: root
    password:
  session:
    dsn: sqlite:%BS_VAR_DIR%/db/session.sqlite3
    loggable: no
  prgr:
    dsn: mysql:host=127.0.0.1;dbname=prgr
    uid: root
  register:
    dsn: pgsql:host=localhost dbname=register user=postgres

smtp:
  host: localhost
  #check_addresses: no

xmpp:
  host: jabber.b-shock.co.jp

awstats:
  log_file: /var/log/httpd/access_%%YYYY%%MM%DD.log
  #log_dir: /var/log/httpd/www.example.com
  #daily: no
  server_name_aliases: 

session:
  #storage_type: database

date:
  timezone: Asia/Tokyo

google:
  key: 0vnLqpBQFHLy7J9p/YO40u6wOrTlaV2I
