<?php
abstract class BSConfigHandler extends ConfigHandler {
	private $body = array();

	public function __construct () {
		$this->putLine('// auth-generated by ' . get_class($this));
		$this->putLine('// date: ' . BSDate::getNow('Y/m/d H:i:s'));
	}

	protected function putLine ($line) {
		$this->body[] = $line;
	}

	protected function getBody () {
		return "<?php\n" . implode("\n", $this->body) . "\n?>";
	}

	protected function getConfig ($path) {
		$file = new BSIniFile($path);
		return $file->getContents();
	}

	public static function literalize ($value) {
		$value = self::replaceConstants($value);
		return parent::literalize($value);
	}

	public static function & replaceConstants ($value) {
		return BSDirectoryFinder::replaceConstants($value);
	}
}

?>