<?php
/**
 * @package jp.co.b-shock.carrot
 * @subpackage config
 */

/**
 * ディレクトリレイアウト設定
 *
 * @author 小石達也 <tkoishi@b-shock.co.jp>
 * @copyright (c)b-shock. co., ltd.
 * @version $Id$
 */
class BSLayoutConfigHandler extends IniConfigHandler {
	public function & execute ($config) {
		$body = array(
			'<?php',
			'// auth-generated by ' . get_class($this),
			'// date: ' . BSDate::getNow('Y/m/d H:i:s'),
		);
		foreach ($this->parseIni($config) as $name => $params) {
			foreach ($params as $key => $value) {
				$body[] = sprintf(
					'$this->directories[%s][%s] = %s;',
					self::literalize($name),
					self::literalize($key),
					self::literalize($value)
				);
			}
		}
		$body[] = '?>';
		$body = implode("\n", $body);

		return $body;
	}

	public static function & replaceConstants ($value) {
		return BSDirectoryFinder::replaceConstants($value);
	}
}

/* vim:set tabstop=4 ai: */
?>