<?php
/**
 * @package jp.co.b-shock.carrot
 * @subpackage config
 */

/**
 * サーバ毎の設定
 *
 * @author 小石達也 <tkoishi@b-shock.co.jp>
 * @copyright (c)b-shock. co., ltd.
 * @version $Id$
 */
class BSServerConfigHandler extends IniConfigHandler {
	public function & execute ($config) {
		$body = array(
			'<?php',
			'// auth-generated by ' . get_class($this),
			'// date: ' . BSDate::getNow('Y/m/d H:i:s'),
		);

		foreach ($this->parseIni($config) as $categoryKey => $category) {
			foreach ($category as $key => $value) {
				if (preg_match('/^\./', $categoryKey)) {
					$name = array('BS', strtoupper($key));
				} else {
					$name = array('BS', strtoupper($categoryKey), strtoupper($key));
				}
				$value = self::replaceConstants($value);
				$body[] = sprintf(
					'define(%s, %s);',
					$this->literalize(implode('_', $name)),
					$this->literalize($value)
				);
			}
		}
		$body[] = '?>';
		$body = implode("\n", $body);

		return $body;
	}

	public static function & replaceConstants ($value) {
		return BSDirectoryFinder::replaceConstants($value);
	}
}

/* vim:set tabstop=4 ai: */
?>